CREATE TABLE mescs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    dataNascimento DATE NOT NULL,
    mae VARCHAR(255),
    pai VARCHAR(255),
    identidade VARCHAR(255) NOT NULL,
    orgaoEmissor ENUM('SSP', 'PF', 'DETRAN', 'OUTRO') DEFAULT 'OUTRO',
    dataExpedicao DATE NOT NULL,
    cpf VARCHAR(14) NOT NULL,
    estadoCivil ENUM('solteiro', 'casado', 'divorciado', 'viuvo') DEFAULT 'solteiro',
    cep VARCHAR(10),
    naturalidade VARCHAR(255) NOT NULL,
    estado ENUM('AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MT', 'MS', 'MG', 'PA', 'PB', 'PR', 'PE', 'PI', 'RJ', 'RN', 'RS', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO') NOT NULL,
    endereco VARCHAR(255),
    numero VARCHAR(10),
    complemento VARCHAR(255),
    bairro VARCHAR(255),
    escolaridade ENUM('fundamental', 'medio', 'superior') DEFAULT 'fundamental',
    profissao VARCHAR(255) NOT NULL,
    telefoneResidencial VARCHAR(20),
    telefoneCelular VARCHAR(20) NOT NULL,
    email VARCHAR(255) NOT NULL,
    paróquia VARCHAR(255),
    movimentosPastorais ENUM('sim', 'nao') DEFAULT 'nao',
    quaisMovimentos VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

